
const MENU_CLICKED = 'MENU_CLICKED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT';

export default { MENU_CLICKED, LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT };