
const MENU_CLICKED = 'MENU_CLICKED';
const LOGIN_INITIATE = 'LOGIN_INITIATE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT_INITIATE = 'LOGOUT_INITIATE';
const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';

export default {
    MENU_CLICKED,
    LOGIN_INITIATE,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_INITIATE,
    LOGOUT_COMPLETE
};